# Generated by Django 4.0.2 on 2022-04-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cate_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_post_name', models.CharField(max_length=255)),
                ('cate_post_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=255)),
                ('post_content', models.CharField(max_length=255)),
                ('post_image', models.ImageField(default=None, upload_to='images')),
                ('post_author', models.CharField(max_length=255)),
                ('cate_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.cate_post')),
            ],
        ),
    ]
