# Generated by Django 4.0.2 on 2022-04-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cate_post',
            name='cate_post_status',
        ),
        migrations.AddField(
            model_name='cate_post',
            name='cate_post_slug',
            field=models.SlugField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(default=None, max_length=255),
        ),
    ]
