# Generated by Django 4.0.2 on 2022-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendors',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='cus_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
