# Generated by Django 4.0.2 on 2022-04-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_vendors_order_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='vendor',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
